name: Qodana
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

jobs:
  qodana:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      checks: write
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-13, macos-latest]
        unity-versions:
          - 6000.0.37f1
        include:
          - os: windows-latest
            build-targets: StandaloneWindows64
            modules: windows-server
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          fetch-depth: 0
      - name: Buildalon Unity Setup
        uses: buildalon/unity-setup@v1
        with:
          unity-version: ${{ matrix.unity-versions }} # overrides version in version-file
          build-targets: ${{ matrix.build-targets }}
          modules: ${{ matrix.modules }}
      - name: Sync Unity Solution for Rider
        run: |
          chmod +x prepare_qodana.sh
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2024.3
        with:
          args: --ide,QDNET
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}